apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-app
spec:
  destination:
    namespace: enterprise-platform
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/your-username/enterprise-multi-cluster-secure-platform
    path: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
